[package]
name = "ingester"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
ngrok = "0.15.0"
tokio = { version = "1.45.1", features = ["full"] }
url = "2.5.4"
reqwest = "0.12.18"
serde = { version = "1.0.219", features = ["derive"] }
